
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

#    url: jdbc:mysql://119.29.145.61:3306/gzjc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
 #   url: jdbc:mysql://119.29.145.61:3306/gzjc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
 #   username: root
 #   password: jckc

    url: jdbc:mysql://123.207.230.97:3306/sign_in_system?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: jckc
