server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms
  servlet:
    session:
      timeout: 7200s


spring:
  # 环境 dev|test|prod 开发/测试/上线
  profiles:
    #    active: test
    active: test


  # 热部署
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false

#    spring.thymeleaf.prefix=classpath:/templates/
#    spring.thymeleaf.suffix=.vm
  thymeleaf:
    cache: true
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传格式
  servlet:
    multipart:
      max-file-size: 10MB # 单个上传最大文件大小
      max-request-size: 100MB  # 单个请求总文件大小
      enabled: true

  # 缓存
  redis:
    open: true # 是否开启redis缓存  true开启   false关闭
    database: 2
    host: 120.78.157.175
    port: 6379
    password: jcredis   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true


# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl  #打印sql日志
    log-prefix:
  mapper-locations: classpath:mapper/*.xml
 # type-aliases-package: com.hc.modules/*/entity


#分页插件
pagehelper:
  auto-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

logging:
  config: classpath:log4j2-spring.xml
  # 设置单个文件最大内存
multipart.maxFileSize: 50Mb
  # 设置所有文件最大内存
multipart.maxRequestSize: 50Mb


